name: WorldBan
version: '1.13.2-BETA'
main: vasys.worldban.WorldBan
api-version: '1.20'
authors: [ Vasys ]
commands:
  worldban:
    description: Ban players in worlds
    usage: /worldban <player> <world>
  worldpardon:
    description: Unban players in worlds
    usage: /worldpardon <player> <world>