name: WorldBan
version: '1.8-SNAPSHOT'
main: vasys.worldban.WorldBan
api-version: '1.20'
authors: [ Vasys ]
commands:
  worldban:
    description: Ban players in worlds
    usage: /worldban <player> <world>